// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestViewEfCore.Models;

public partial class Enfants
{
    public int NumDos { get; set; }

    public string Nom { get; set; }

    public string Prenom { get; set; }

    public DateTime? DateNais { get; set; }

    public string RangNais { get; set; }

    public byte Clo { get; set; }

    public short? CoordId { get; set; }

    public string Sexe { get; set; }

    public byte FratrieRang { get; set; }

    public byte FratrieNb { get; set; }

    public int? AssureId { get; set; }

    public DateTime? DateMaj { get; set; }

    public short? ReferentId { get; set; }

    public string NumDosPap { get; set; }

    public int? FratrieId { get; set; }

    public string MdphNum { get; set; }

    public DateTime? DateNaisC { get; set; }

    public string NirCertif { get; set; }

    public bool HasConsentMsc { get; set; }

    public bool HasConsentMss { get; set; }

    public bool HasConsentDmp { get; set; }

    public virtual ICollection<Inss> InsIndex { get; } = new List<Inss>();
}